#ifndef RESOLUTION_H
#define RESOLUTION_H

#define MENU_HEIGHT 30
#define MONSTER_HEIGHT 56
#define MONSTER_WIDTH 56
#define STATUS_HEIGHT 30
#define MARGIN 5
#define LIFE_WIDTH 30
#define LIFE_HEIGHT 3
#define LIFE_WIDTH_MARGIN 20
#define LEVEL_HEIGHT 14

#define STATUS_MARGIN (MENU_HEIGHT + MARGIN + STATUS_HEIGHT)
#define MONSTER_OWN_MARGIN (STATUS_MARGIN + MARGIN + MONSTER_HEIGHT)
#define LIFE_OWN_MARGIN (STATUS_MARGIN + MARGIN + LIFE_HEIGHT)
#define LIFE_ENEMY_MARGIN (MARGIN + LEVEL_HEIGHT)



#endif
